<form method="post" action="https://checkout.ionia.app/api/purchase" style="width:100%;">
    <!-- USER INFORMATION -->
    <input type="visible" name="UserEmail" value="user@example.com" />
    <input type="visible" name="UserMobileNumber" value="+1 1234567890" />

    <!-- BILLING INFORMATION -->
    <input type="visible" name="Billing_Address1" value="123 Main St." />
    <input type="visible" name="Billing_Address2" value="Suite 100" />
    <input type="visible" name="Billing_City" value="Anytown" />
    <input type="visible" name="Billing_State" value="CA" />
    <input type="visible" name="Billing_Zip" value="12345" />
    <input type="visible" name="Billing_Country" value="US" />

    <!-- PURCHASE DETAILS -->
    <input type="hidden" name="GrandTotal" value="57.84" />
    <input type="hidden" name="MerchantId" value="ABC" />
    <input type="hidden" name="OrderId" value="123" />
    <input type="hidden" name="AmountOfPurchase" value="51.23" />
    <input type="hidden" name="Tax" value="4.61" />
    <input type="hidden" name="PurchaseItemText" value="Widget ABC" />
    <input type="hidden" name="ShippingAmount" value="2.00" />

    <!-- UTILITY INFORMATION -->
    <input type="hidden" name="ReturnUrl" value="/purchase-success" />
    <input type="hidden" name="ReturnUrlCancel" value="/purchase-cancel" />
    <input type="hidden" name="ReturnUrlFailure" value="/purchase-failure" />
    <input type="hidden" name="BrandPrimaryColor" value="#FF9900" />
    <input type="hidden" name="BrandSecondaryColor" value="#aaa" />
    <input type="hidden" name="LogoUrl" value="https://example.com/logo.png" />

    <div class="d-flex justify-center">
        <button type="submit" class="btn btn-warning btn-lg">Complete Purchase</button>
    </div>
</form>