<div class="mud-layout" style=""><div class="mud-main-content"><h2 class="mud-typography mud-typography-h2 mud-typography-gutterbottom mud-typography-align-center">CONTINUOUS POST METHOD</h2>

<div class="mud-container mud-container-maxwidth-lg mud-container--gutters mt-16"><h3 class="mud-typography mud-typography-h3 mud-typography-gutterbottom mud-typography-align-center">Pricing</h3>
    <p class="mud-typography mud-typography-body1 mud-typography-align-center">
        This method is where the user clicks the purchase button, it POSTS the data, and takes the user to the Ionia purchase page which completes the purchase
        process, and takes the user back to this page to finish the process. 
    </p>
    <div class="mud-grid mud-grid-spacing-xs-6 justify-start mt-8"><div class="mud-grid-item mud-grid-item-xs-12 mud-grid-item-sm-6 mud-grid-item-md-4"><div class="mud-paper mud-elevation-25 mud-card rounded-lg pb-4" style=""><div class="mud-card-header"><div class="mud-card-header-content"><h5 class="mud-typography mud-typography-h5 mud-typography-align-center">Amazon Product</h5></div></div>
                <div class="mud-card-content"><div class="d-flex justify-center"><h3 class="mud-typography mud-typography-h3">$5</h3></div>
                    <div class="mud-list mx-auto mt-4" style="width:300px;"><div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Email & Phone OPTIONALLY Populated
                            <div class="mud-input-control mud-input-outlined-with-label mud-input-input-control"><div class="mud-input-control-input-container"><div class="mud-input mud-input-outlined mud-input-outlined-with-label mud-shrink mud-typography-input"><input class="mud-input-slot mud-input-root mud-input-root-outlined" id="mudinputcvw8mt06" type="text" value="chris@ionia.io" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="mud-input-slot mud-input-root mud-input-root-outlined" style="display:none" tabindex="-1"></div><div class="mud-input-outlined-border"></div></div><label class="mud-input-label mud-input-label-animated mud-input-label-outlined mud-input-label-inputcontrol" for="mudinputcvw8mt06">Email Address</label></div></div>
                            <div class="mud-input-control mud-input-outlined-with-label mud-input-input-control"><div class="mud-input-control-input-container"><div class="mud-input mud-input-outlined mud-input-outlined-with-label mud-shrink mud-typography-input"><input class="mud-input-slot mud-input-root mud-input-root-outlined" id="mudinputjn2ehpxj" type="text" value="4805400060" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="mud-input-slot mud-input-root mud-input-root-outlined" style="display:none" tabindex="-1"></div><div class="mud-input-outlined-border"></div></div><label class="mud-input-label mud-input-label-animated mud-input-label-outlined mud-input-label-inputcontrol" for="mudinputjn2ehpxj">Mobile Phone</label></div></div></p></div></div>
                        <div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Logo Url Supplied
                        </p></div></div>
                        <div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Branded Color Supplied
                        </p></div></div>
                        <div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            6 Separate Products Added
                        </p></div></div></div></div>
                <form method="post" action="https://test.checkout.ionia.app/api/purchase" style="width:100%;"><input type="hidden" name="GrandTotal" value="1418.14">
                    <input type="hidden" name="MerchantId" value="ABC">
                    <input type="hidden" name="ReturnUrl" value="/return-success">
                    
                    





                    
                    
                    <input type="hidden" name="UserEmail" value="chris@ionia.io" />
                    <input type="hidden" name="UserMobileNumber" value="4805400060" />

                    
                    <input type="hidden" name="Billing_Address1" value="2846 Bridge Avenue">
                    <input type="hidden" name="Billing_Address2" value>
                    <input type="hidden" name="Billing_City" value="Dallas">
                    <input type="hidden" name="Billing_State" value="TX">
                    <input type="hidden" name="Billing_Zip" value="94404">
                    <input type="hidden" name="Billing_Country" value="USA">

                    
                    <input type="hidden" name="OrderId" value="123">
                    <input type="hidden" name="AmountOfPurchase" value="51.23">
                    <input type="hidden" name="Tax" value="4.61">
                    <input type="hidden" name="ShippingAmount" value="2.00">


                    
                    
                    <input type="hidden" name="PurchaseItemsJson" value='[
                        {"Name":"Dell Laptop", "Quantity":1, "PricePerUnit":1240, "ProductImageUrl": "https://m.media-amazon.com/images/I/61gAWTw6FAL.jpg"},
                        {"Name":"Burrito Blanket", "Quantity":1, "PricePerUnit":19.99, "ProductImageUrl": "https://m.media-amazon.com/images/I/71O8qk9St3L._AC_SL1500_.jpg"},
                        {"Name":"Banana Phone Bluetooth Handset for iPhone", "Quantity":1, "PricePerUnit":39.99, "ProductImageUrl": "https://m.media-amazon.com/images/I/41KiRdhYfiL._AC_SL1399_.jpg"},
                        {"Name":"Keyboard", "Quantity":2, "PricePerUnit":67.54, "ProductImageUrl": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/peripherals/input-devices/dell/keyboards/kb900/media-gallery/keyboard-kb900-black-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=804&wid=1898&qlt=100,1&resMode=sharp2&size=1898,804&chrss=full"},
                        {"Name":"Cables", "Quantity":3, "PricePerUnit":12.15, "ProductImageUrl": "https://m.media-amazon.com/images/I/81SRr8OFuuL._SL1500_.jpg"},
                        {"Name":"Wool Socks", "Quantity":2, "PricePerUnit":19.95, "ProductImageUrl": "https://m.media-amazon.com/images/I/91CQy27yLTL._AC_SX679_.jpg"}]'>


                    
                    <input type="hidden" name="ReturnUrlCancel" value="http://localhost:39777/?page=purchase-cancel">
                    <input type="hidden" name="ReturnUrlFailure" value="http://localhost:39777/?page=purchase-failure">
                    <input type="hidden" name="ReturnUrlEditCart" value="/return-editcart.phtml">
                    <input type="hidden" name="BrandPrimaryColor" value="#FF9900">
                    <input type="hidden" name="BrandSecondaryColor" value="#aaa">
                    <input type="hidden" name="LogoUrl" value="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/2560px-Amazon_logo.svg.png">

                    <div class="mud-card-actions d-flex justify-center"><button type="submit" class="mud-button-root mud-button mud-button-filled mud-button-filled-warning mud-button-filled-size-large mud-ripple" __internal_stopPropagation_onclick><span class="mud-button-label">PURCHASE AMAZON</span></button></div></form></div></div>
        <div class="mud-grid-item mud-grid-item-xs-12 mud-grid-item-sm-6 mud-grid-item-md-4"><div class="mud-paper mud-elevation-25 mud-card rounded-lg pb-4" style=""><div class="mud-card-header"><div class="mud-card-header-content"><h5 class="mud-typography mud-typography-h5 mud-typography-align-center">Netflix</h5></div></div>
                <div class="mud-card-content"><div class="d-flex justify-center"><h3 class="mud-typography mud-typography-h3">$10</h3></div>
                    <div class="mud-list mx-auto mt-4" style="width:300px;"><div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Email & Phone NOT Populated
                        </p></div></div>
                        <div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Logo supplied
                        </p></div></div>
                        <div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Branded color supplied
                        </p></div></div></div></div>
                <form method="post" action="https://test.checkout.ionia.app/api/purchase" style="width:100%;"><input type="hidden" name="Billing_Address1" value="2846 Bridge Avenue">
                    <input type="hidden" name="Billing_Address2" value>
                    <input type="hidden" name="Billing_City" value="Dallas">
                    <input type="hidden" name="Billing_State" value="TX">
                    <input type="hidden" name="Billing_Zip" value="94404">
                    <input type="hidden" name="Billing_Country" value="USA">

                    
                    <input type="hidden" name="GrandTotal" value="57.84">
                    <input type="hidden" name="MerchantId" value="ABC">
                    <input type="hidden" name="OrderId" value="123">
                    <input type="hidden" name="AmountOfPurchase" value="51.23">
                    <input type="hidden" name="Tax" value="4.61">
                    <input type="hidden" name="ShippingAmount" value="2.00">

                    
                    <input type="hidden" name="ReturnUrl" value="/purchase-success">
                    <input type="hidden" name="ReturnUrlCancel" value="http://localhost:39777/?page=purchase-cancel">
                    <input type="hidden" name="ReturnUrlFailure" value="http://localhost:39777/?page=purchase-failure">
                    <input type="hidden" name="BrandPrimaryColor" value="#E50914">
                    <input type="hidden" name="BrandSecondaryColor" value="#aaa">
                    <input type="hidden" name="LogoUrl" value="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png">
                    <div class="mud-card-actions d-flex justify-center"><button type="submit" class="mud-button-root mud-button mud-button-filled mud-button-filled-error mud-button-filled-size-large mud-ripple" __internal_stopPropagation_onclick><span class="mud-button-label">PURCHASE NETFLIX</span></button></div></form></div></div>
        <div class="mud-grid-item mud-grid-item-xs-12 mud-grid-item-sm-12 mud-grid-item-md-4"><div class="mud-paper mud-elevation-25 mud-card rounded-lg pb-4" style=""><div class="mud-card-header"><div class="mud-card-header-content"><h5 class="mud-typography mud-typography-h5 mud-typography-align-center">No Brand</h5></div></div>
                <div class="mud-card-content"><div class="d-flex justify-center"><h3 class="mud-typography mud-typography-h3">$15</h3></div>
                    <div class="mud-list mx-auto mt-4" style="width:300px;"><div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Email & Phone OPTIONALLY Populated
                            <div class="mud-input-control mud-input-outlined-with-label mud-input-input-control"><div class="mud-input-control-input-container"><div class="mud-input mud-input-outlined mud-input-outlined-with-label mud-shrink mud-typography-input"><input class="mud-input-slot mud-input-root mud-input-root-outlined" id="mudinputncm1jsb4" type="text" value="chris@ionia.io" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="mud-input-slot mud-input-root mud-input-root-outlined" style="display:none" tabindex="-1"></div><div class="mud-input-outlined-border"></div></div><label class="mud-input-label mud-input-label-animated mud-input-label-outlined mud-input-label-inputcontrol" for="mudinputncm1jsb4">Email Address</label></div></div>
                            <div class="mud-input-control mud-input-outlined-with-label mud-input-input-control"><div class="mud-input-control-input-container"><div class="mud-input mud-input-outlined mud-input-outlined-with-label mud-shrink mud-typography-input"><input class="mud-input-slot mud-input-root mud-input-root-outlined" id="mudinput4a1ukb2a" type="text" value="4805400060" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="mud-input-slot mud-input-root mud-input-root-outlined" style="display:none" tabindex="-1"></div><div class="mud-input-outlined-border"></div></div><label class="mud-input-label mud-input-label-animated mud-input-label-outlined mud-input-label-inputcontrol" for="mudinput4a1ukb2a">Mobile Phone</label></div></div></p></div></div>
                        <div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            NO branded color supplied
                        </p></div></div>
                        <div tabindex="0" class="mud-list-item mud-list-item-gutters mud-list-item-clickable mud-ripple" __internal_stopPropagation_onclick><div class="mud-list-item-icon"><svg class="mud-icon-root mud-svg-icon mud-icon-size-medium" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class="mud-list-item-text"><p class="mud-typography mud-typography-body1">
                            Lorem ipsum
                        </p></div></div></div></div>
                <form method="post" action="https://test.checkout.ionia.app/api/purchase" style="width:100%;"><input type="hidden" name="UserEmail" value="chris@ionia.io" />
                    <input type="hidden" name="UserMobileNumber" value="4805400060" />

                    
                    <input type="hidden" name="Billing_Address1" value="2846 Bridge Avenue">
                    <input type="hidden" name="Billing_Address2" value>
                    <input type="hidden" name="Billing_City" value="Dallas">
                    <input type="hidden" name="Billing_State" value="TX">
                    <input type="hidden" name="Billing_Zip" value="94404">
                    <input type="hidden" name="Billing_Country" value="USA">

                    
                    <input type="hidden" name="GrandTotal" value="57.84">
                    <input type="hidden" name="MerchantId" value="ABC">
                    <input type="hidden" name="OrderId" value="123">
                    <input type="hidden" name="AmountOfPurchase" value="51.23">
                    <input type="hidden" name="Tax" value="4.61">
                    <input type="hidden" name="ShippingAmount" value="2.00">

                    
                    <input type="hidden" name="ReturnUrl" value="/purchase-success">
                    <input type="hidden" name="ReturnUrlCancel" value="http://localhost:39777/?page=purchase-cancel">
                    <input type="hidden" name="ReturnUrlFailure" value="http://localhost:39777/?page=purchase-failure">

                    <div class="mud-card-actions d-flex justify-center"><button type="submit" class="mud-button-root mud-button mud-button-filled mud-button-filled-info mud-button-filled-size-large mud-ripple" __internal_stopPropagation_onclick><span class="mud-button-label">PURCHASE NO BRAND COLOR</span></button></div></form></div></div></div></div>

                    <div style="margin-bottom:100px;">&nbsp;</div></div></div>



<div class="mud-popover-provider"></div>
