<!doctype html>
<html lang="en">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<div class="" style=""><div class=""><h2 class="">CONTINUOUS POST METHOD</h2>

<! This section is for the Pricing header and subtext indicating how the purchase buttons work >
<div class="container px-4 py-5" id="featured=3"><h3 class="">Pricing</h3>
<!  Subtext for header>
<p class="">
        This method is where the user clicks the purchase button, it POSTS the data, and takes the user to the Ionia purchase page which completes the purchase
        process, and takes the user back to this page to finish the process. 
    </p>
    <! This is the Amazon Product Mock
    This is meant to test for a customer that is already in the Ionia Pay Checkout system.>
    <div class=""><div class=""><div class="" style=""><div class=""><div class=""><h5 class="">Amazon Product</h5></div></div>
                <div class=""><div class=""><h3 class="">$5</h3></div>
    <! This is the table that lists the test info for the Amazon Product Purchase
    The first div class sets the alignment and list style
    The style width determines how many pxiels can be displayed on a single line
    >
                    <div class="" style="width;300px"><div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Email & Phone OPTIONALLY Populated
                            <div class=""><div class=""><div class=""><input class="" id="" type="text" value="chris@ionia.io" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="" style="display:none" tabindex="-1"></div><div class=""></div></div><label class="" for="mudinputcvw8mt06">Email Address</label></div></div>
                            <div class=""><div class=""><div class=""><input class="" id="" type="text" value="4805400060" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="" style="display:none" tabindex="-1"></div><div class=""></div></div><label class="" for="mudinputjn2ehpxj">Mobile Phone</label></div></div></p></div></div>
                        <div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Logo Url Supplied
                        </p></div></div>
                        <div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Branded Color Supplied
                        </p></div></div>
                        <div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            6 Separate Products Added
                        </p></div></div></div></div> >
                <form method="post" action="https://test.checkout.ionia.app/api/purchase" style="width:100%;"><input type="hidden" name="GrandTotal" value="1418.14">
                    <input type="hidden" name="MerchantId" value="ABC">
                    <input type="hidden" name="ReturnUrl" value="/return-success">
                    
                    





                    
                    <!Here their email and phone number will come prefilled.>
                    <input type="hidden" name="UserEmail" value="chris@ionia.io" />
                    <input type="hidden" name="UserMobileNumber" value="4805400060" />

                    <!this is an automated input for the address that comes cooked in with the email and number>
                    <input type="hidden" name="Billing_Address1" value="2846 Bridge Avenue">
                    <input type="hidden" name="Billing_Address2" value>
                    <input type="hidden" name="Billing_City" value="Dallas">
                    <input type="hidden" name="Billing_State" value="TX">
                    <input type="hidden" name="Billing_Zip" value="94404">
                    <input type="hidden" name="Billing_Country" value="USA">

                    <!These input OrderID value and the different cost and associated taxes for the purchase>
                    <input type="hidden" name="OrderId" value="123">
                    <input type="hidden" name="AmountOfPurchase" value="51.23">
                    <input type="hidden" name="Tax" value="4.61">
                    <input type="hidden" name="ShippingAmount" value="2.00">


                    
                    <!This is a premade list of amazon items that relate to the purchase. Name changes the item name, quantity sets the quantity of how many are purchased, PricePerUnit determines the cost of each item and the ProductImageUrl changes the thumbnail for the items>
                    <input type="hidden" name="PurchaseItemsJson" value='[
                        {"Name":"Dell Laptop", "Quantity":1, "PricePerUnit":1240, "ProductImageUrl": "https://m.media-amazon.com/images/I/61gAWTw6FAL.jpg"},
                        {"Name":"Burrito Blanket", "Quantity":1, "PricePerUnit":19.99, "ProductImageUrl": "https://m.media-amazon.com/images/I/71O8qk9St3L._AC_SL1500_.jpg"},
                        {"Name":"Banana Phone Bluetooth Handset for iPhone", "Quantity":1, "PricePerUnit":39.99, "ProductImageUrl": "https://m.media-amazon.com/images/I/41KiRdhYfiL._AC_SL1399_.jpg"},
                        {"Name":"Keyboard", "Quantity":2, "PricePerUnit":67.54, "ProductImageUrl": "https://i.dell.com/is/image/DellContent/content/dam/ss2/product-images/peripherals/input-devices/dell/keyboards/kb900/media-gallery/keyboard-kb900-black-gallery-1.psd?fmt=png-alpha&pscan=auto&scl=1&hei=804&wid=1898&qlt=100,1&resMode=sharp2&size=1898,804&chrss=full"},
                        {"Name":"Cables", "Quantity":3, "PricePerUnit":12.15, "ProductImageUrl": "https://m.media-amazon.com/images/I/81SRr8OFuuL._SL1500_.jpg"},
                        {"Name":"Wool Socks", "Quantity":2, "PricePerUnit":19.95, "ProductImageUrl": "https://m.media-amazon.com/images/I/91CQy27yLTL._AC_SX679_.jpg"}]'>


                    <input type="hidden" name="BaseUrl"= value="http://localhost:39777" >
                    <input type="hidden" name="ReturnUrlCancel" value="/purchase-cancel.phtml">
                    <input type="hidden" name="ReturnUrlFailure" value="/purchase-failure.phtml">
                    <input type="hidden" name="ReturnUrlEditCart" value="/return-editcart.phtml">
                    <input type="hidden" name="BrandPrimaryColor" value="#FF9900">
                    <input type="hidden" name="BrandSecondaryColor" value="#aaa">
                    <input type="hidden" name="LogoUrl" value="https://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Amazon_logo.svg/2560px-Amazon_logo.svg.png">

                    <div class=""><button type="submit" class="" __internal_stopPropagation_onclick><span class="">PURCHASE AMAZON</span></button></div></form></div></div>
        <div class=""><div class="" style=""><div class=""><div class=""><h5 class="">Netflix</h5></div></div>
                <div class=""><div class=""><h3 class="">$10</h3></div>
                    <div class="" style="width:300px;"><div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Email & Phone NOT Populated
                        </p></div></div>
                        <div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Logo supplied
                        </p></div></div>
                        <div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Branded color supplied
                        </p></div></div></div></div>
                <form method="post" action="https://test.checkout.ionia.app/api/purchase" style="width:100%;"><input type="hidden" name="Billing_Address1" value="2846 Bridge Avenue">
                    <input type="hidden" name="Billing_Address2" value>
                    <input type="hidden" name="Billing_City" value="Dallas">
                    <input type="hidden" name="Billing_State" value="TX">
                    <input type="hidden" name="Billing_Zip" value="94404">
                    <input type="hidden" name="Billing_Country" value="USA">

                    
                    <input type="hidden" name="GrandTotal" value="57.84">
                    <input type="hidden" name="MerchantId" value="ABC">
                    <input type="hidden" name="OrderId" value="123">
                    <input type="hidden" name="AmountOfPurchase" value="51.23">
                    <input type="hidden" name="Tax" value="4.61">
                    <input type="hidden" name="ShippingAmount" value="2.00">

                    
                    <input type="hidden" name="ReturnUrl" value="/purchase-success">
                    <input type="hidden" name="BaseUrl"= value="http://localhost:39777" >
                    <input type="hidden" name="ReturnUrlCancel" value="/purchase-cancel.phtml">
                    <input type="hidden" name="ReturnUrlFailure" value="/purchase-failure.phtml">
                    <input type="hidden" name="BrandPrimaryColor" value="#E50914">
                    <input type="hidden" name="BrandSecondaryColor" value="#aaa">
                    <input type="hidden" name="LogoUrl" value="https://upload.wikimedia.org/wikipedia/commons/7/7a/Logonetflix.png">
                    <div class=""><button type="submit" class="" __internal_stopPropagation_onclick><span class="">PURCHASE NETFLIX</span></button></div></form></div></div>
        <div class=""><div class="" style=""><div class=""><div class=""><h5 class="">No Brand</h5></div></div>
                <div class=""><div class=""><h3 class="">$15</h3></div>
                    <div class="" style="width:300px;"><div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Email & Phone OPTIONALLY Populated
                            <div class=""><div class=""><div class=""><input class="" id="mudinputncm1jsb4" type="text" value="chris@ionia.io" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="" style="display:none" tabindex="-1"></div><div class=""></div></div><label class="" for="mudinputncm1jsb4">Email Address</label></div></div>
                            <div class=""><div class=""><div class=""><input class="" id="mudinput4a1ukb2a" type="text" value="4805400060" inputmode="text" maxlength="524288" aria-invalid="false" aria-required="false" /><div class="" style="display:none" tabindex="-1"></div><div class=""></div></div><label class="" for="mudinput4a1ukb2a">Mobile Phone</label></div></div></p></div></div>
                        <div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            NO branded color supplied
                        </p></div></div>
                        <div tabindex="0" class="" __internal_stopPropagation_onclick><div class=""><svg class="" focusable="false" viewBox="0 0 24 24" aria-hidden="true" role="img"><path d="M0 0h24v24H0z" fill="none"/><path d="M19 2H5c-1.11 0-2 .9-2 2v14c0 1.1.89 2 2 2h4l3 3 3-3h4c1.1 0 2-.9 2-2V4c0-1.1-.9-2-2-2zm-6 16h-2v-2h2v2zm2.07-7.75-.9.92C13.45 11.9 13 12.5 13 14h-2v-.5c0-1.1.45-2.1 1.17-2.83l1.24-1.26c.37-.36.59-.86.59-1.41 0-1.1-.9-2-2-2s-2 .9-2 2H8c0-2.21 1.79-4 4-4s4 1.79 4 4c0 .88-.36 1.68-.93 2.25z"/></svg></div><div class=""><p class="">
                            Lorem ipsum
                        </p></div></div></div></div>
                <form method="post" action="https://test.checkout.ionia.app/api/purchase" style="width:100%;"><input type="hidden" name="UserEmail" value="chris@ionia.io" />
                    <input type="hidden" name="UserMobileNumber" value="4805400060" />

                    
                    <input type="hidden" name="Billing_Address1" value="2846 Bridge Avenue">
                    <input type="hidden" name="Billing_Address2" value>
                    <input type="hidden" name="Billing_City" value="Dallas">
                    <input type="hidden" name="Billing_State" value="TX">
                    <input type="hidden" name="Billing_Zip" value="94404">
                    <input type="hidden" name="Billing_Country" value="USA">

                    
                    <input type="hidden" name="GrandTotal" value="57.84">
                    <input type="hidden" name="MerchantId" value="ABC">
                    <input type="hidden" name="OrderId" value="123">
                    <input type="hidden" name="AmountOfPurchase" value="51.23">
                    <input type="hidden" name="Tax" value="4.61">
                    <input type="hidden" name="ShippingAmount" value="2.00">

                    <input type="hidden" name="BaseUrl"= value="http://localhost:39777" >
                    <input type="hidden" name="ReturnUrl" value="/purchase-success">
                    <input type="hidden" name="ReturnUrlCancel" value="/purchase-cancel.phtml">
                    <input type="hidden" name="ReturnUrlFailure" value="/purchase-failure.phtml">

                    <div class=""><button type="submit" class="" ><span class="">PURCHASE NO BRAND COLOR</span></button></div></form></div></div></div></div>

                    <div style="margin-bottom:100px;">&nbsp;</div></div></div>



<div class=""></div>
</html>