<!doctype html>
<html lang="en">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
<body>

      
    
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">

  <symbol id="toggles2" viewBox="0 0 16 16">
    <path d="M9.465 10H12a2 2 0 1 1 0 4H9.465c.34-.588.535-1.271.535-2 0-.729-.195-1.412-.535-2z"></path>
    <path d="M6 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6zm0 1a4 4 0 1 1 0-8 4 4 0 0 1 0 8zm.535-10a3.975 3.975 0 0 1-.409-1H4a1 1 0 0 1 0-2h2.126c.091-.355.23-.69.41-1H4a2 2 0 1 0 0 4h2.535z"></path>
    <path d="M14 4a4 4 0 1 1-8 0 4 4 0 0 1 8 0z"></path>
  </symbol>
</svg>
<main>

  <div class="container px-4 py-5" id="hanging-icons"> <h2 class="pb-2 border-bottom">Test Pay Methods</h2>
    <div class="row g-4 py-5 row-cols-1 row-cols-lg-2">
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"></use></svg>
        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Continuous Post Method</h3>
          <p>This method is where the user clicks the purchase button, it POSTS the data, and takes the user to the Ionia purchase page which completes the purchase
        process, and takes the user back to this page to finish the process.</p>
          <a href="continuous-post-method.phtml" class="btn btn-primary">
            Go to Continuous Post Method
          </a>
        </div>
      </div>
      <div class="col d-flex align-items-start">
        <div class="icon-square text-body-emphasis bg-body-secondary d-inline-flex align-items-center justify-content-center fs-4 flex-shrink-0 me-3">
          <svg class="bi" width="1em" height="1em"><use xlink:href="#toggles2"></use></svg>
        </div>
        <div>
          <h3 class="fs-2 text-body-emphasis">Continuous Querrystring Method</h3>
          <p>This method is where the user clicks the purchase button, it performs a "get" or querystring parameter method of getting
        the parameters to the server, it then takes the user to the Ionia purchase page which completes the purchase
        process, and takes the user back to this page to finish the process.</p>
          <a href="continuous-querrystring-method.phtml" class="btn btn-primary">
            Go to Continuous Querrystring Method
          </a>
        </div>
      </div>
      </div>
    </div>
  </div>
</main>
<script src="/docs/5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

    

</body>
</html>